### ISSUE TITLE
`prefix` call doesn't check that the current buffer is in `sh-mode`

### ISSUE THREAD

**Issue by dgutov** [Alexander-Miller/company-shell#2]
You just call `company-grab-symbol`. As a result, this backend is unsuitable for the global value of `company-backends`, because it will take over in non-shell buffers too.

**Comment by Alexander-Miller** [comment]
That's working as intended actually. This plugin started because I wanted `sh-mode's` completions available in `fish-mode` but didn't quite understand and duplicate what `sh-mode` was doing with its completion at point functions. I also exclusively use grouped backends so the issue never really entered my mind.

Completing shell functions might also be useful outside of directly writing shell-scripts, so I think a good solution here would be a variable that optionally defines which major modes to provide completions for.

**Comment by dgutov** [comment]
Yes, a variable like `company-clang-modes` should work fine.

**Comment by Alexander-Miller** [comment]
Patch is up.

**Comment by dgutov** [comment]
:thumbsup:
